version: "3.3"

services:

  proxy:
    image: ghcr.io/viasnake/mcserver-proxy
    ports:
      - target: 25565
        published: 25565
        protocol: tcp
        mode: host
      - target: 19132
        published: 19132
        protocol: udp
        mode: host
    environment:
      - JE_BACKEND_ADDRESS=127.0.0.1
      - JE_BACKEND_PORT=25565
      - BE_BACKEND_ADDRESS=127.0.0.1
      - BE_BACKEND_PORT=19132
